# Generated by Django 5.1 on 2024-09-11 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('motto', models.CharField(max_length=255)),
                ('studentImg', models.ImageField(upload_to='static/asset/data_student_image/')),
            ],
        ),
    ]
