# Generated by Django 5.1 on 2024-09-11 06:32

import kelas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstudent',
            name='studentImg',
            field=models.ImageField(blank=True, null=True, upload_to=kelas.models.filepath),
        ),
    ]
