# Generated by Django 5.1 on 2024-09-11 09:01

import kelas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0002_alter_aboutstudent_studentimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKegiatan', models.CharField(max_length=200)),
                ('desKegiatan', models.CharField(max_length=300)),
                ('imgKegiatan', models.ImageField(blank=True, null=True, upload_to=kelas.models.filepath)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
