# Generated by Django 5.1 on 2024-09-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0003_galery'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutstudent',
            name='about',
            field=models.CharField(max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='aboutstudent',
            name='hobi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='aboutstudent',
            name='skils',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
