# Generated by Django 5.1 on 2024-09-17 03:37

import kelas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelas', '0004_aboutstudent_about_aboutstudent_hobi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutstudent',
            name='studentImg',
            field=models.ImageField(null=True, upload_to=kelas.models.filepath),
        ),
    ]
